package gui;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;


/**
 * @team HISIA
 * @member Carlos Castillo
 * @member Luis Daniel Erazo
 * @member Ximena Puchaicela
*/
public class DetectingGUI extends javax.swing.JFrame {
    /**
     * Creates new form Main
     */
    public DetectingGUI() {
        initComponents();
        adjustImage();
        setLocationRelativeTo(null);
        
    }
    
    private void adjustImage(){
        ImageIcon originalImage = new ImageIcon(getClass().getResource("/images/faceDetecting.gif"));
        Image newImage = originalImage.getImage().getScaledInstance(
                this.lblDetectingImage.getWidth(), this.lblDetectingImage.getHeight(), 
                Image.SCALE_DEFAULT);
        Icon newIcon = new ImageIcon(newImage);
        this.lblDetectingImage.setIcon(newIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblDectecting = new javax.swing.JLabel();
        lblDetectingImage = new javax.swing.JLabel();
        txtEmotionDetected = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDectecting.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblDectecting.setText("Opdage (Agente Detector)");
        jPanel3.add(lblDectecting, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 240, 40));
        jPanel3.add(lblDetectingImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 350, 330));

        txtEmotionDetected.setEditable(false);
        txtEmotionDetected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmotionDetectedActionPerformed(evt);
            }
        });
        jPanel3.add(txtEmotionDetected, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 140, 40));

        jLabel1.setText("Emoción detectada");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Se podria agregar un emoticon");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 250, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmotionDetectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmotionDetectedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmotionDetectedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetectingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetectingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetectingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetectingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetectingGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblDectecting;
    private javax.swing.JLabel lblDetectingImage;
    public javax.swing.JTextField txtEmotionDetected;
    // End of variables declaration//GEN-END:variables
}