package gui;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;


/**
 * @team HISIA
 * @member Carlos Castillo
 * @member Luis Daniel Erazo
 * @member Ximena Puchaicela
*/
public class SearchGUI extends javax.swing.JFrame {
    /**
     * Creates new form Main
     */
    public SearchGUI() {
        initComponents();
        adjustImage();
        setLocationRelativeTo(null);
        
    }
    
    private void adjustImage(){
        ImageIcon originalImage = new ImageIcon(getClass().getResource("/images/searching.gif"));
        Image newImage = originalImage.getImage().getScaledInstance(
                this.lblSearchImage.getWidth(), this.lblSearchImage.getHeight(), 
                Image.SCALE_DEFAULT);
        Icon newIcon = new ImageIcon(newImage);
        this.lblSearchImage.setIcon(newIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblSearching = new javax.swing.JLabel();
        lblSearchImage = new javax.swing.JLabel();
        lblEmotionSearch = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSearching.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblSearching.setText(" Raadso (Agente Buscador)");
        jPanel3.add(lblSearching, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 240, 40));
        jPanel3.add(lblSearchImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 300, 330));
        jPanel3.add(lblEmotionSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 390, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    public javax.swing.JLabel lblEmotionSearch;
    private javax.swing.JLabel lblSearchImage;
    private javax.swing.JLabel lblSearching;
    // End of variables declaration//GEN-END:variables
}